# Generated by Django 4.2.29 on 2026-04-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('icon', models.CharField(default='ellipsis-horizontal', max_length=50)),
                ('color', models.CharField(default='#9CA3AF', max_length=7)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='families.family')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('family', 'Family')], default='medium', max_length=10)),
                ('google_event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='families.familymember')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='families.family')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='families.familymember')),
            ],
            options={
                'unique_together': {('event', 'family_member')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['family', 'date'], name='events_even_family__3f414b_idx'),
        ),
    ]
